spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://localhost:3306/step?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none #create , create-drop , update , validate, none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace # sql 로그 생성 활성화
